name: run scratch
on:
    #Triggers the workflow on push or pull request events but onlu for the devTest branch
    pull_request:
        types: [opened, synchronize]
    # Jobs to be executed
jobs:
    validate_scratch_deploy:
        runs-on: ubuntu-latest
        if: ${{github.actor != 'dependabot[bot]'}}
        steps:
            #Checkout the source code
            - name: 'Checkout source code'
              uses: actions/checkout@v3
            
            #Install Salesforce CLI
            - name: 'Install Salesforce CLI'
              run: |
                    npm install @salesforce/cli --location=global
                    nodeInstallPath=$(npm config get prefix)
                    echo "$nodeInstallPath/bin" >> $GITHUB_PATH
                    sf --version
            
            # Load secret for dev hub
            - name: "Populate auth file with SFDX_URL secret"
              shell: bash
              run: "echo ${{ secrets.DEVHUB_SFDX_URL}} > ./SFDX_URL_STORE.txt"
            
            #Authenticate dev hub
            - name: 'Authenticate Dev Hub'
              run: sf org login sfdx-url -f ./SFDX_URL_STORE.txt -a devhub -d
               
            #Create scratch org  
            - name: 'Create scratch org'
              run:  sf org login sfdx-url -f ./SFDX_URL_STORE.txt -a devhub -d
              
            # Deploy source to scratch org sf project deploy start --target-org devhub
            - name: 'Push source to scratch org'
              run: sf project deploy start --source-dir force-app/main/default/classes --target-org devhub --concise 

            #Run Apex tests in scratch org
            #- name: 'Run Apex tests'
            #  run: sf apex run test -c -r human -d --target-org devhub 
            
            # Delete temporary test file thatr CodeCov is unable to parse
            #- name: 'Delete coverage file (temporary step)'
             # run: rm ./tests/apex/test-result-707*-codecoverage.json
              
            # Upload code coverage  data
            - name: 'Upload code coverage for Apex to CodeCov.io'
              uses: codecov/codecov-action@v2.0.2
              with:
                   flags: Apex
              
            # Housekeeping
            - name: 'Delete scratch org'
              if: always()
              run: sf org delete scratch --target-org devhub 
              
            
            
            
              
