/**
 * @description       : 
 * @author            : Patrick Randrianarisoa
 * @group             : 
 * @last modified on  : 11-09-2023
 * @last modified by  : Patrick Randrianarisoa
 * Modifications Log
 * Ver   Date         Author                   Modification
 * 1.0   11-09-2023   Patrick Randrianarisoa   Initial Version
**/
@isTest
public class DocumentVersionDetails_CST_TST {

    @isTest
    static void testDoAfterUpdateFlag() {
        DocumentVersionDetails_CST.DoAfterUpdate = true;
    }
}