name: run push 
on :
  push:
        branches: DEV
jobs: 
    action-pull-request:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2
          with:
              fetch-depth: 0
        - name: Run the Action
          if: startsWith(github.ref, 'refs/heads/DEV')
          uses: devops-infra/action-pull-request@v0.4.2
          env: 
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with: 
             github_token: ${{ secrets.GITHUB_TOKEN }}
             title: Automatic Pull Request
             get_diff: true
             
    creation-pr-uat:
          runs-on: ubuntu-latest
          steps: 
          # Checkout the source code
              - name: 'Checkout source code'
                uses: actions/checkout@v4
                with:
                  repository: roddyTelesio/REPO-UAT
                  ref: 'UAT'
                  token:  ${{ secrets.GITHUB_TOKEN }}
                  fetch-depth: 0
          # Create pull-request to UATT
              - name: Create PR in UAT
                run: |
                    git remote add UAT1 https://github.com/roddyTelesio/REPO-UAT.git
                    git fetch UAT1 
                    git checkout -b UAT1
                    git config --global user.email roddy.randrianarison@telesio.fr
                    git config --global user.name roddy.randrianarison@axa-re.com.uat
                    git cherry-pick ${{ github.event.pull_request.head.sha}} --commit

